// src/redux/actions/types.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const FETCH_RECIPE_DETAILS_SUCCESS = 'FETCH_RECIPE_DETAILS_SUCCESS';
export const FETCH_RECIPE_DETAILS_FAILURE = 'FETCH_RECIPE_DETAILS_FAILURE';
export const FETCH_INGREDIENT_SUGGESTIONS_SUCCESS = 'FETCH_INGREDIENT_SUGGESTIONS_SUCCESS';
export const FETCH_INGREDIENT_SUGGESTIONS_FAILURE = 'FETCH_INGREDIENT_SUGGESTIONS_FAILURE';
export const CLEAR_INGREDIENT_SUGGESTIONS = 'CLEAR_INGREDIENT_SUGGESTIONS';

